# -*- coding: utf-8 -*-
"""Capture the source decks' speaker notes verbatim into _m6_notes.py.

Notes are keyed by SOURCE slide number, not by rebuilt slide number, so the
capture stays valid however the rebuild renumbers.  Run once; _m6_notes.py is
then a build input and is edited only to add notes, never to reword a
captured one (Teaching CLAUDE.md: preserve substantive notes verbatim).
"""
from pathlib import Path
from pptx import Presentation

SRC = Path("Module 6 - NV Slides")
DECKS = [("NV", SRC / "Module 6.pptx"),
         ("APP", SRC / "Module 6 -- Slides On-Campus Applications with "
                       "Solutions.pptx")]
DECKS += [("V%d" % k, SRC / ("Module 6 - Video %d.pptx" % k))
          for k in range(1, 9)]

out = ["# -*- coding: utf-8 -*-",
       '"""Speaker notes captured VERBATIM from the Module 6 source decks.',
       "",
       "Generated by _make_notes.py -- do not reword a captured note here;",
       "override it in the build script instead (the Module 4 pattern).",
       "Keys are SOURCE slide numbers.",
       '"""', ""]
for tag, deck in DECKS:
    prs = Presentation(str(deck))
    d = {}
    for i, s in enumerate(prs.slides, 1):
        if not s.has_notes_slide:
            continue
        tf = s.notes_slide.notes_text_frame
        txt = (tf.text or "").strip() if tf is not None else ""
        # A PollEverywhere slide's notes ARE the poll mechanism -- keep them
        # out of here so nothing can reword them; _splice_media.py carries
        # the whole notes part across verbatim.
        if txt and "Poll Title: Do not modify the notes" not in txt:
            d[i] = txt
    out.append("NOTES_%s = {" % tag)
    for k in sorted(d):
        out.append("    %d: %r," % (k, d[k]))
    out.append("}")
    out.append("")
    print("%-4s %2d notes" % (tag, len(d)))
Path("_m6_notes.py").write_text("\n".join(out), encoding="utf-8")
print("-> _m6_notes.py")
