# -*- coding: utf-8 -*-
"""
Speaker-notes source of truth for Class 1. Teleprompter-style narration for a
general reader (first person, read-aloud, a bit more background), time-neutral,
no dash-asides. Anecdotes ~1 in 3, set off as a paragraph starting 'ANECDOTE — '.

SKIP sets (no notes): logistics 3-9, agenda (roadmap 10 + section dividers),
poll slides (protected PollEverywhere notes), trailing blanks 133-135.
Slide 17 keeps its existing 'More info on Celts' line, appended after the note.
Backups 105-131 get one brief orienting line each (132 is a poll).
"""

SKIP_LOGISTICS = {3, 4, 5, 6, 7, 8, 9}
SKIP_AGENDA = {10, 12, 18, 30, 32, 41, 46, 56, 65, 68, 92}
SKIP_POLL = {11, 13, 21, 35, 48, 69, 132}
SKIP_BLANK = {133, 134, 135}
SLIDE17_KEEP = "More info on Celts: https://en.wikipedia.org/wiki/Celts"

# Source / further-reading link for each anecdote (appended after the anecdote).
ANECDOTE_SOURCES = {
    14: "https://en.wikipedia.org/wiki/Sassi_di_Matera",
    19: "https://en.wikipedia.org/wiki/Romulus_and_Remus",
    22: "https://en.wikipedia.org/wiki/Augustus",
    25: "https://en.wikipedia.org/wiki/Publican",
    27: "https://en.wikipedia.org/wiki/Edict_on_Maximum_Prices",
    28: "https://en.wikipedia.org/wiki/Romulus_Augustulus",
    31: "https://en.wikipedia.org/wiki/Emirate_of_Sicily",
    33: "https://en.wikipedia.org/wiki/Carroccio",
    34: "https://en.wikipedia.org/wiki/The_Allegory_of_Good_and_Bad_Government",
    43: "https://en.wikipedia.org/wiki/Luca_Pacioli",
    44: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci",
    45: "https://en.wikipedia.org/wiki/Milan_Cathedral",
    47: "https://en.wikipedia.org/wiki/The_Betrothed_(Manzoni_novel)",
    49: "https://en.wikipedia.org/wiki/Iron_Crown_of_Lombardy",
    57: "https://en.wikipedia.org/wiki/Giuseppe_Garibaldi",
    58: "https://en.wikipedia.org/wiki/Expedition_of_the_Thousand",
    61: "https://en.wikipedia.org/wiki/Italian_unification",
    64: "https://en.wikipedia.org/wiki/Lingotto",
    66: "https://en.wikipedia.org/wiki/March_on_Rome",
    71: "https://en.wikipedia.org/wiki/Marshall_Plan",
    90: "https://en.wikipedia.org/wiki/Vespa",
    91: "https://en.wikipedia.org/wiki/Luxottica",
    100: "https://en.wikipedia.org/wiki/Mani_pulite",
}

NOTES = {
1: """Welcome to Class 1 of our International Business Residential in Italy. Before we say a single word about economics, I want you to just look at the country we are about to study and then visit in person. Over the next hour we are going to tell one long story, starting three thousand years ago and ending with the Italy we will actually walk into in Milan and Turin. My promise is simple. By the end, the modern Italian economy, with all its strengths and all its puzzles, will make a lot more sense.""",

2: """This is our home base for the whole session. I'm Nico Voigtländer, and this is the big-picture class that sets up everything we do on the trip. The theme I want you to hold onto is that Italy's economy today is not an accident. It is the product of a very long history, and again and again we will see the same forces at work: geography, trade, the strength or weakness of institutions, and the way regions pull apart and come back together.""",

14: """The first thing to understand is that "Italy" begins as many cultures, not one. The two images make the point across the whole length of the peninsula. On the left are the Sassi of Matera, in the deep south, a town of dwellings carved straight into the rock. On the right are the prehistoric rock carvings of Valcamonica, in the north, one of the largest collections of petroglyphs anywhere in the world, including the famous figure people nicknamed "The Astronaut." So the roots here are both very deep and very varied.

ANECDOTE — Matera is worth a story. People lived in those stone caves more or less continuously for nine thousand years, but by the 1950s families were still sharing them with their animals, and the poverty was so severe that a leading Italian politician called Matera "the shame of the nation." The government emptied the caves and moved everyone out. Then the story completely flips. Today Matera is a UNESCO World Heritage site, it was a European Capital of Culture in 2019, and it stands in for ancient Jerusalem in films from The Passion of the Christ to the James Bond movie No Time to Die. It is a nice reminder that "poor and backward" and "world-class asset" can be the very same place just a few decades apart.""",

15: """This is a slide about geography shaping destiny, so let the relief map do the work. Notice the Alps sealing off the top and the Apennine mountains running like a spine straight down the middle. That rugged terrain made moving goods overland slow and expensive. The consequence runs through the entire course. It was far cheaper to ship by sea, so the Italian economy turned outward to the Mediterranean, and those same mountains chopped the interior into many separate cities and regions that often had more contact with the coast than with each other.""",

16: """The Etruscans were central Italy's first advanced civilization, flourishing from around 800 BC. They were a league of independent cities rather than a single state, they grew wealthy from mining and the metal trade, and they had their own art and written alphabet before Rome amounted to much. The image is the famous Sarcophagus of the Spouses. Notice how the husband and wife recline together as equals at a banquet, which tells us Etruscan women enjoyed a social standing that later Romans found striking. By around 500 BC Rome had absorbed them, but Rome inherited a great deal in the process, including the arch, practical engineering, and the alphabet.""",

17: """Use the map to take in just how crowded and plural the peninsula still was. There were Celts across the north, Greeks along the south, and the Latins of Rome rising in the center. After 500 BC Rome's language and influence spread outward in a long process of Romanization. Here is the point that tends to surprise people. The Greek south, known as Magna Graecia, was then the richer and more urban half, and it handed Italy coinage, vines, and olives, which are still core exports today. So the North-South gap we will study later is not written in the stars. Early on, it actually ran the other way.""",

19: """Now we get to Rome itself. The city was founded, by tradition, in 753 BC, and the legend of the twin brothers Romulus and Remus raised by a she-wolf is the founding myth every Italian schoolchild knows. What matters for us is why this spot succeeded. Point to the map and note the practical advantages: a natural ford to cross the river Tiber, which made it a trading crossroads, and easily defended hills. Rome started as a kingdom and then, in 509 BC, became a republic, which is where its real institutional story begins.

ANECDOTE — The founding legend has a darker turn that says something about Rome. The twins argued over where to build the city and how high its walls should be, and in the quarrel Romulus killed his own brother Remus. Rome, in other words, told a story about itself in which the city is born from ambition, rivalry, and a willingness to defend its boundary at any cost. For a civilization that would go on to conquer the Mediterranean, that origin story fits.""",

20: """The Roman Republic gave us something that outlived the Romans by two thousand years: a system of checks and balances. Walk down the structure on the slide. There were elected magistrates who ran the state, like the consuls, drawn from both commoners and aristocrats. There was the Senate, an unelected but hugely powerful assembly of the aristocracy. And there were the popular assemblies that voted on laws and elections. The system eventually broke down in the crisis of the first century BC, when Julius Caesar made himself dictator and was murdered in 44 BC, but the deepest legacy is Roman law itself, the law of property, contracts, and the legal "person," which is the direct ancestor of European commercial law.""",

22: """Out of that breakdown came the empire. Caesar's adopted son Octavian defeated Mark Antony and Cleopatra and became the first emperor, Augustus, ruling from 27 BC to 14 AD. What followed was about two centuries of relative peace and prosperity that we call the Pax Romana, a golden age for literature and architecture. The statue on the slide is the Augustus of Prima Porta, the classic image of the confident young ruler, arm raised, addressing his people. That pose was propaganda, and it worked.

ANECDOTE — Augustus understood image as well as any modern CEO. The historian Suetonius reports his boast that he had found Rome a city of brick and left it a city of marble. It was partly literal, because he did launch a huge building program, and partly a claim about the whole enterprise: that he had taken something ordinary and made it monumental.""",

23: """This slide is here to let the architecture speak, so linger on the images. On the left is the Pantheon, whose unreinforced concrete dome is still the largest of its kind in the world, nearly two thousand years after it was poured. On the right is the Colosseum, which could hold tens of thousands of spectators and emptied through a system of numbered entrances that stadium designers still admire. The point is not nostalgia. It is that Roman engineering, concrete, arches, and roads, was a genuine general-purpose technology that powered the economy.""",

24: """This is the same Pax Romana, now told as an economic story. Under two centuries of relative peace there were few major wars, though Britain was conquered between 43 and 87 AD, and trade flourished, reaching all the way to silk and spices from the East. The image is the Via Appia, the great Roman road, still paved with its original basalt stones. Roads like this, together with safe sea lanes, are what turned a collection of provinces into a single working economy.""",

25: """Here is the big economic idea of the Roman section, so slow down. Rome created what was effectively the first large integrated market: one currency, the silver denarius, a network of roads, and safe sea lanes across a Mediterranean the Romans called "our sea," Mare Nostrum. On top of that sat Roman law, with property rights and enforceable contracts, the foundation later European business would run on. Grain, wine, oil, and luxuries moved freely across the whole empire. The image is a Roman denarius. The lesson to carry forward is that Rome's prosperity came from integration: one market, common rules, shared infrastructure, and security.

ANECDOTE — The Romans even had something that looks like the stock market. Public contracts, from tax collection to supplying the army, were run by companies called publicani, and shares in those companies could be bought and sold. The historian Polybius marveled that people all over Rome had a stake in these ventures. It is a striking early glimpse of the corporation and the tradeable share, roughly seventeen centuries before Amsterdam.""",

26: """This map is worth a pause because it shows the sheer scale of what Rome integrated. This is the empire at its greatest extent, around 117 AD, at the death of the emperor Trajan. The red is the empire proper and the pink marks client states. Trace the ring around the Mediterranean with your eye. Everything inside that boundary shared a currency, a body of law, and a road network. When we later talk about the European single market, remember that Rome got there first, and that holding it together was the whole challenge.""",

27: """Every integrated system can also come apart, and Rome shows how. After a run of the so-called Five Good Emperors ending in 180 AD, the very centralization that made Rome strong became its weakness, because a single bad emperor now did immediate, empire-wide damage. There was decadence and mismanagement, constant fighting over the succession, and, crucially for economists, fiscal overreach and the debasement of the coinage, which fed serious inflation. The map shows the barbarian invasions pressing in from every side. The point is that political and monetary rot arrived together.

ANECDOTE — The emperor Diocletian tried to fight the inflation by decree. In 301 AD he issued an Edict on Maximum Prices, setting legal ceilings for something like a thousand goods and services, from a day's wages to a pound of pork. It failed almost immediately, because merchants simply pulled their goods off the market rather than sell at a loss. It is one of history's oldest and clearest lessons in what price controls do.""",

28: """This is the end of the story, at least for the West. In 395 AD the empire formally split into East and West. The Western half, including Rome, suffered wave after wave of invasions, and in 476 AD a Germanic commander named Odoacer deposed the last Western emperor and made himself ruler of Italy. The Eastern half carried on for another thousand years as the Byzantine Empire. The image is a coin of Odoacer. The economic headline is on the slide: as the empire fragmented, the single market broke into local economies, and trade, cities, and coinage all shrank.

ANECDOTE — History has a sense of irony here. The last emperor of the West was a teenage boy named Romulus Augustulus, which means "little Augustus." So the Western empire that began with a founder named Romulus and a first emperor named Augustus ended with a powerless child who carried both names at once.""",

29: """Let me draw the section together on this slide, because it sets up everything that follows. Overextension, a debased currency, and insecurity broke the integrated market apart. Money, trade, and cities all localized, and Italy splintered into many small economies, which you can see on the fragmentation map. For roughly the next thousand years, prosperity would have to be rebuilt slowly, city by city, and that rebuilding is exactly where the story goes next, with the medieval communes. The line to remember is simple: what integration builds, dis-integration destroys.""",

31: """The centuries after Rome are traditionally called the Dark Ages, a time of economic, intellectual, and cultural decline across the former Western empire. For Italy the defining feature was fragmentation and constant outside rule. The map of power kept getting redrawn, with, for example, Muslim rule in Sicily and the south, later taken over by the Normans, while the north was pulled into the Holy Roman Empire. That difference matters enormously. In the north, towns increasingly governed themselves, while the south was ruled from the top down, and that split is the deep historical root of the North-South divide we still study today.

ANECDOTE — The "Dark Ages" were not dark everywhere. Arab-ruled Sicily went through a genuine farming revolution, as Muslim rulers introduced citrus, sugar cane, cotton, and sophisticated irrigation. A lot of what we now think of as quintessentially Italian, the lemons of the south included, arrived on the back of that period. It is a good reminder to be skeptical of the label "dark."
""",

33: """Now the recovery begins, and it begins in the northern towns. From the eleventh century there was a Commercial Revolution, helped along by the Crusades from 1095, which reopened trade routes to the East and slowly brought back the trade in spices and silk. As commerce grew, cities gained real economic and political weight. They banded together in the Lombard League to resist the Holy Roman Emperor, Frederick Barbarossa, and famously beat him at the Battle of Legnano in 1176, winning the right to govern their own affairs at the Peace of Constance in 1183. The image is Siena's Piazza del Campo, the public heart of exactly this kind of self-governing city. And out on the water, the maritime republics of Venice, Genoa, Pisa, and Amalfi came to dominate Mediterranean trade.

ANECDOTE — The Lombard League fought under a strange and wonderful symbol: the Carroccio, a large ox-drawn wagon carrying an altar, a bell, and the city's banner, which was wheeled into the middle of the battlefield. It was part rallying point and part sacred object, and losing it was a disgrace. It captures something about these towns, that civic and religious pride was worth risking your life for.""",

34: """Why do those self-governing towns still matter economically, eight hundred years later? Because running your own affairs was a kind of training. These independent cities had real autonomy over their economy, their taxes, and their courts, and exercising that self-government built up habits of cooperation and trust that scholars call "social capital." The image is Ambrogio Lorenzetti's fresco in Siena's town hall, the "Effects of Good Government," which literally paints a well-run, prosperous city. Keep that idea of social capital in mind, because the next slides show it can be measured and that it persists.

ANECDOTE — Lorenzetti painted that fresco around 1338, right on the town hall wall, as a daily reminder to the officials working there of what good and bad government produce. Tellingly, the "Good Government" side, with its busy, happy city, has survived far better than the decayed "Bad Government" side across the room. Even the paint seems to have taken sides.""",

36: """This is one of the featured research papers for the course, so it is worth flagging what we are about to do. The paper is called "Long-Term Persistence," by Guiso, Sapienza, and Zingales, three very well known economists, two of them with deep Italian roots. The question they tackle is the one we just raised: does the medieval experience of self-government still shape economic life in Italy today? The next few slides walk through how they answer it.""",

37: """The clever part of the paper is how they measure something as fuzzy as social capital. They use three concrete proxies for it today: the number of nonprofit organizations per person, whether a town has an organ-donation association, and how often schoolchildren cheat on a standardized national exam. The main finding is on the slide, and it is striking. Towns in the north that were independent city-states around the year 1200 have significantly more social capital today, centuries after those medieval republics disappeared.""",

38: """This chart shows the first proxy, nonprofit organizations. Point to the gap: towns that had the free-city experience in the Middle Ages have measurably more civic and nonprofit organizations now. The dashed line and the average tell the story. What you are looking at is history that refuses to fade. A political arrangement from eight hundred years ago is still visible in how densely people organize themselves today.""",

39: """Here are the other two proxies, and they point the same way. Former free cities have more organ-donation organizations, a sign of trust in strangers and in institutions, and their students cheat less on the national exam, a sign of everyday honesty. None of these measures is perfect on its own, which is exactly why the authors use three of them. When independent measures all line up, the pattern is hard to dismiss.""",

40: """Now the payoff, and it connects directly to the trip. Italy's south has less social capital today, and the paper's argument is historical: the south was taken over by the Normans in the eleventh to thirteenth centuries, a tight, top-down rule that never allowed independent self-governing cities to form. The south is also much less economically developed today, and the claim is that these two facts are linked, that the gap in economic performance flows in part from that persistent difference in social capital. The map makes it vivid: it shows Italian regions shaded by GDP per person, and the north is plainly richer than the south. When we are in Milan and Turin, we are standing in the heartland of the old free cities.""",

42: """We arrive at the Renaissance, which for us is first and foremost an economic story. From the thirteenth to the sixteenth century the independent city-states of northern Italy grew rich, and that wealth is what we mean by the economic "rebirth." They pioneered financial innovations we still use, from banking practices to accounting to tradeable bonds, and they pushed shipbuilding and navigation in the search for new trade routes, the same search that led to the discovery of America. The image is the dome of Florence's cathedral, engineered by Brunelleschi. The sequence matters: commercial wealth, combined with political freedom, is what funded the explosion of art and science we usually think of first.""",

43: """This slide is the one to dwell on, because it is the heart of why Italy matters to a business school. In the Renaissance, Italy essentially invented the toolkit of modern business. Double-entry bookkeeping was codified by a monk named Luca Pacioli in 1494 and is still the basis of accounting worldwide. The gold florin of Florence, shown here, became an international reserve currency, the dollar of its day. Merchant banks like the Medici, Bardi, and Peruzzi financed kings and popes, and Italians developed bills of exchange, marine insurance, and venture partnerships. Venice's Arsenal was even building ships on something close to an assembly line, centuries before Henry Ford.

ANECDOTE — Luca Pacioli, the man who codified double-entry bookkeeping, was a close friend of Leonardo da Vinci. They shared a house for a time, and Leonardo drew the illustrations for Pacioli's book on mathematical proportion. So the "father of accounting" and the ultimate Renaissance genius were literally collaborators, which tells you that in this world, finance and art were not separate universes.""",

44: """Leonardo da Vinci is the human face of this era, so let the images carry it. Painter, engineer, anatomist, inventor, he is the model of the Renaissance mind that moved freely between art and technology. For our purposes he is not just a great artist. He is a symbol of a culture where curiosity, patronage, and money flowed together to produce extraordinary things.

ANECDOTE — Here is a very modern detail. When Leonardo wanted a job with the Duke of Milan, he wrote what amounts to a cover letter, and it survives. He spends almost the entire letter selling himself as a military engineer, listing portable bridges, cannons, and siege machines he could build. Only at the very end, almost as an afterthought, does he mention that he can also paint and sculpt. Even the greatest artist in history knew he had to pitch what the customer was actually buying.""",

45: """A closing look at Renaissance building, and again the images do the talking. On the slide are Milan's cathedral and Venice's Marciana Library, two very different statements of civic and religious ambition. The point to make is that architecture on this scale required not just genius but organization, financing, and patience across generations.

ANECDOTE — Milan's Duomo is the extreme case of patience. Construction began in 1386, and the cathedral was not considered truly finished until the twentieth century, with the last details completed in the 1960s. Italians even have a saying, "like building the Duomo," for a task that never seems to end. When we stand in front of it in Milan, remember it took roughly six hundred years.""",

47: """After the Renaissance peak comes a long decline, and the cause is partly bad luck of geography. When the Americas were discovered, the center of gravity of world trade shifted from the Mediterranean to the Atlantic, and the Italian city-states, brilliant at Mediterranean commerce, were suddenly off to the side. There is a bitter irony that Columbus was himself Genoese, but he sailed for Spain, and the Atlantic powers reaped the gains. Meanwhile the south fell under Spanish rule, with a refeudalization that entrenched barons and great estates, and heavy taxes to fund Spain's wars. The image is a painting of a plague, a reminder that epidemics repeatedly savaged Italy in this period, including the 1630 outbreak that devastated the northern cities.

ANECDOTE — That 1630 plague is burned into Italian culture through the country's most famous novel, Alessandro Manzoni's The Betrothed, required reading in Italian schools. Manzoni describes the hysteria in Milan, including the hunt for so-called untori, people accused of deliberately smearing plague onto walls and doors to spread it. It is an early and chilling portrait of how fear turns a public-health disaster into a search for scapegoats.""",

49: """Spain's grip on Italy loosened after 1700, and the peninsula fell back into a patchwork of small states, until an outsider reorganized everything. Napoleon conquered most of Italy between 1796 and 1809, and, whatever you think of the conquest, the reforms mattered. He imposed the Napoleonic legal code, swept away the old guilds, introduced the metric system, and put in place a more meritocratic administration. He even created a sovereign Italian state in the northeast, with its own flag. In effect, Napoleon dragged Italy toward modern institutions, sometimes at the point of a bayonet.

ANECDOTE — In 1805 Napoleon had himself crowned King of Italy in Milan's cathedral, using the ancient Iron Crown of Lombardy, said to contain a nail from the Crucifixion. As he placed it on his own head, he is reported to have declared, "God gave it to me; beware anyone who touches it." Modesty was never his problem.""",

50: """Now we pivot from history to a piece of live economics, using Italy as a natural laboratory. The question is important and genuinely unsettled: does copyright actually encourage people to create more and better work? It is hard to answer because copyright laws are usually not random. Successful artists may lobby for protection precisely because they already earn a lot, so you cannot just compare places with and without copyright. Yet U.S. law simply assumes the connection, stating that the purpose of copyright is to foster creation, and there has been remarkably little hard evidence for that assumption.""",

51: """This is the second featured paper, "Copyright and Creativity: Evidence from Italian Operas," by Michela Giorcelli, who is here at UCLA, and Petra Moser at NYU. Note that Michela Giorcelli is someone whose work we will see twice today, and she studies exactly these questions using rich historical Italian data. Opera turns out to be the perfect testing ground, and the next slides explain why.""",

52: """The images set the scene: nineteenth-century Italy was opera-mad, and operas are wonderfully well documented, so we can actually measure how many were written, how popular they were, and how long they lasted. That is what makes this a rare chance to see the effect of copyright on creativity in real data rather than in theory. Keep in mind the puzzle from a moment ago, that normally you cannot untangle copyright from everything else going on.""",

53: """Here is the elegant trick that makes the study work. The authors gathered data on nearly 2,600 operas that premiered across Italy between 1770 and 1900, along with measures of how popular and durable each one became. Then they use Napoleon as the source of randomness. Northern Italy, Lombardy and Venetia, was annexed first and adopted French laws, including copyright, in 1801, while the rest of Italy was annexed later and got no copyright. So they can compare composers in the copyright regions to composers elsewhere, where the difference in the law was essentially an accident of conquest, not of lobbying.""",

54: """This map shows the setup: which parts of Italy fell under Napoleon, and therefore under copyright, first. The lightly shaded regions are the ones that got copyright protection early. The whole research design rests on this geography, so it is worth pointing to. The comparison is between these early-copyright areas and the rest of the peninsula.""",

55: """And here is the result, which is clear on both counts. On quantity, Lombardy and Venetia produced about 2.2 times more operas per year after copyright arrived in 1801. On quality, the works from the copyright regions were more popular and more durable, the ones still performed and recorded today. So in this natural experiment, copyright really did spur more creation, and better creation. It is one of the cleanest pieces of evidence we have that intellectual-property protection can pay off in more and better art.""",

57: """Now to how modern Italy was actually built, which is a genuinely dramatic story. Keep in mind that Italy had not been a single country for about thirteen hundred years, and after Napoleon fell in 1814 it went right back to being a patchwork of states under foreign influence. Waves of riots and revolts tried, and failed, to unite it as a republic. The central figure is Giuseppe Garibaldi, whose early life reads like an adventure novel: he led an uprising in 1834 and was sentenced to death, fled to South America and learned guerrilla warfare, returned to fight in 1848, lost again, and ended up in exile.

ANECDOTE — Part of that exile was spent in New York. Garibaldi lived on Staten Island and, for a time, worked in a candle factory owned by a fellow Italian exile, Antonio Meucci, who himself has a claim to inventing the telephone. The house is still there as a museum. The future hero of Italian unification once punched a clock as an immigrant worker just outside Manhattan.""",

58: """Unification finally succeeded because the patriots learned from their failures. They accepted two hard truths: small separate states were too weak to fight Austria and France alone, and there was no broad popular appetite for a republic. So the new plan in 1860 was pragmatic: enlist French help to push out the Austrians, even at the price of handing Nice and Savoy to France, and aim for a strong monarchy under Piedmont's King Victor Emmanuel II rather than a republic. Garibaldi did his part brilliantly, conquering first Sicily and then the Kingdom of Naples, and then, in a remarkable act of restraint, handed the whole south over to the king.

ANECDOTE — Garibaldi took the entire south with a volunteer force of about a thousand men, the famous Expedition of the Thousand, known for their red shirts. That red shirt became such a potent symbol that "Redshirts" entered the political vocabulary. It is one of the rare times in history that roughly a thousand irregulars toppled a kingdom.""",

59: """These images capture the human drama of unification, so let them breathe. On one side, Sicilian peasants welcoming Garibaldi as a liberator in 1860. On the other, the almost theatrical moment when Garibaldi meets King Victor Emmanuel II and hands over the south. That handshake is the deal that made Italy a monarchy rather than a republic. It is worth noting how much of this turned on a few personalities and choices.""",

60: """Unification was a political triumph, but economically the new country started in a deep hole. Italy in 1861 was overwhelmingly agrarian and barely industrialized, with high illiteracy, a jumble of dialects, and no efficient infrastructure tying the peninsula together. Crucially, the national market that unification created was built on northern terms, northern law, the northern currency, and tariffs that suited northern industry. The 1887 tariff is the clearest example, protecting northern manufacturers while hurting southern farmers, and in the decades that followed millions of southerners emigrated, turning parts of the south into a remittance economy. The painting is of an Italian peasant, a reminder of who most Italians actually were at unification.""",

61: """This slide drives home just how divided the new nation was. The heterogeneity was enormous. Culturally and linguistically, the country barely shared a language: by one well-known estimate, only around 3 percent of people in Italy in 1861 actually spoke Italian in daily life. Economically, the north had been a market economy and was much richer, while the south had been a protectionist, poorer state with a thin entrepreneurial class, and the southern economy actually collapsed after 1870. This is the origin of the phrase the "Southern Question," and of the mass emigration that followed.

ANECDOTE — There is a famous line, often attributed to the statesman Massimo d'Azeglio, that captures the moment perfectly: "We have made Italy; now we must make Italians." Whoever said it first, the point stands. In 1861 Italy was a state on a map long before it was a people who felt Italian, and building that shared identity took generations.""",

62: """Let's put numbers on the story with the Maddison data, the standard long-run estimates of GDP per person. Walk the line from 1800 to 1945 and note that Italy grows, but slowly, and stays poor by Western European standards for most of this period. The takeaway is that political unification in the 1860s did not deliver an economic miracle. That would have to wait almost another century.""",

63: """Same data, now as a comparison, which is where it really bites. Line Italy up against the other major economies over 1800 to 1945 and the gap is obvious: Italy is the laggard, well behind Britain, Germany, and the United States. This is the sobering baseline. Whatever its glorious past, by the early twentieth century Italy was a relatively poor European country, and everyone knew it.""",


64: """So how did Italy start to catch up? Industry came late, from the 1890s, and it clustered tightly in the northern triangle of Milan, Turin, and Genoa, powered by cheap hydroelectric power from the Alps. This is where the names you will recognize appear: Fiat founded in 1899, Pirelli in 1872, Olivetti in 1908, financed in the German style by big universal banks. And in 1933 the state itself became a giant industrialist, creating IRI, a holding company that ended up owning steel, shipping, and telecoms, a public-enterprise model that shaped Italian capitalism all the way into the 1990s. The image is Fiat's Lingotto factory in Turin, a temple of early Italian industry, and a place whose spirit we will feel on the trip.

ANECDOTE — The Lingotto factory had one unforgettable feature: a test track on the roof. Cars were assembled floor by floor as they rose through the building and then driven out onto a banked racetrack five stories up to be tested. It became so iconic that it starred in the original 1969 film The Italian Job, in a car chase across the rooftop. Industrial engineering as theater.""",

66: """Between that early industrialization and the postwar boom comes the dark chapter of Fascism. Set the scene: Italy in the early 1920s was chaos, with mass strikes, high unemployment, and street fighting between left-wing and right-wing militias. A frightened middle class wanted order, and Mussolini's movement promised exactly that. After a general strike in 1922, Mussolini staged his "March on Rome," and the king, rather than resist, simply handed him power. From there Mussolini dismantled democracy and built a dictatorship and a personality cult.

ANECDOTE — The "March on Rome" was more theater than march. Mussolini himself did not march at all; he traveled up to Rome comfortably by overnight train from Milan, and the decisive move was the king's refusal to call out the army. It is a useful reminder that authoritarian takeovers often succeed less by force than by everyone else deciding not to stop them.""",

67: """Fascism led Italy into catastrophe. Mussolini backed Franco in the Spanish Civil War, signed the "Pact of Steel" with Nazi Germany in 1939, and dragged an unprepared country into the Second World War, where by 1943 Italy was militarily broken. The king had Mussolini arrested, but the Germans sprang him and set him up as the puppet ruler of a rump state in the north. What followed was effectively a civil war, with Italian partisans fighting Italian Fascists and occupying German troops, until the surrender in the spring of 1945. Italy emerged from the war poor, divided, and physically wrecked.""",

70: """Now we reach the period that most directly explains modern Italy, and the story has a twist that management students will love. When we tally the war damage, only about 10 percent of Italy's physical capital had actually been destroyed. The bigger problem was how firms were run. The quotations on the slide, from contemporary observers, describe factories that were disorganized, poorly lit, badly maintained, with old-fashioned sales and distribution. The image is the reconstruction of a bombed bridge near Rome. The key insight, which the research will confirm, is that the lack of good management was a more severe problem than the physical war damage.""",

71: """Into this situation came the Marshall Plan, America's enormous program to help Western Europe recover after the war. Between 1948 and 1951 the United States poured in financial aid and in-kind goods on a scale that is hard to grasp: roughly 130 billion in today's dollars, on the order of 5 percent of U.S. GDP in a single year. The images show how central it was to the era. What I want you to notice is that the plan was not only about money and machines. Part of it was about ideas, and that part is where the Italian story gets really interesting.

ANECDOTE — The plan is named for George Marshall, the U.S. Secretary of State who proposed it in a short speech at Harvard in 1947. It worked so well, and did so much to stabilize postwar Europe, that Marshall was awarded the Nobel Peace Prize in 1953, the only career soldier ever to receive it.""",

72: """These are contemporary posters and cartoons promoting the Marshall Plan, so let the images speak. Notice how the aid was sold to the public, as partnership, recovery, and a shared future, on both sides of the Atlantic. Propaganda is not always a dirty word; here it was part of rebuilding confidence. It is a nice window into how a huge economic policy was communicated to ordinary people.""",

73: """Within the Marshall Plan sat a specific and, for us, fascinating effort: the Productivity Program, running from 1952 to 1958. It had two prongs. One sent European managers on training trips to American firms to learn how they operated. The other offered loans that could only be used to buy technologically advanced machines from the United States. In Italy the program targeted small and medium-sized manufacturers, and participation was voluntary. Hold onto that word "voluntary," because it creates a problem we will have to solve in a moment.""",

74: """This slide details what the managers actually learned on those study trips, and it is strikingly concrete. Teams of fifteen to twenty people spent eight to twelve weeks inside several American firms in their own industry, sitting in seminars, meeting experts, and working side by side with U.S. managers. The image gives a flavor of the era. The training even had a name, Training Within Industry. This was not abstract theory; it was hands-on transfer of how to run a factory.""",

75: """Here is the actual curriculum, and notice how modern it looks. The Americans taught regular machine maintenance and workplace safety, production planning and order control, systematic training and supervision of workers, continuous improvement of methods, and, importantly, marketing, including market research, branding, design, advertising, and modern distribution. In other words, the whole apparatus of professional management that we now take for granted. For postwar Italian firms, much of this was genuinely new.""",

76: """The other half of the program was capital, and the two halves were deliberately linked. Firms got subsidized loans to buy modern American machines at low interest rates, but the money came with knowledge attached. Italian engineers took four to seven week study trips to learn how to actually use the equipment, backed by three years of technical assistance at home. The image shows a Fiat factory running on new Marshall Plan machinery. The philosophy was that a machine you do not know how to use is just expensive scrap.""",

77: """Before we look at the results, we have to confront the problem I flagged earlier, because it is the heart of doing good economics. Participation was voluntary, so the firms that signed up were probably already different from those that did not. They likely had more motivated managers who were curious about modern methods in the first place. That is the "endogeneity" problem: if you just compare participants to non-participants, you cannot tell whether the program helped or whether the go-getters would have thrived anyway. The treatment group and the control group are not truly comparable.""",

78: """This brings us to Michela Giorcelli's paper again, "The Long-Term Effects of Management and Technology Transfers." This is the study that cracks the problem we just described. The reason it has become so influential is that it finds a clever way to compare like with like, and thereby isolate the true effect of better management. The next slides show how.""",

79: """Here is the research design, and it is worth understanding because it is a model of careful work. Giorcelli assembled data on more than 6,000 Italian firms that were eligible for the program, with their balance sheets from five years before to fifteen years after. The trick is an unexpected U.S. budget cut. Some firms that had already applied and been approved still got their funding and training, while others, equally eligible and equally eager, were cut off purely because the money ran out. Comparing those two groups is almost like a randomized experiment, because which side of the cut you landed on had nothing to do with how good your firm was.""",

80: """This map shows the setting, the five pilot regions where the program ran, against the rest of Italy. Orient the reader: these are the areas where eligible firms could take part. Establishing exactly where and to whom the program applied is what lets the author draw clean comparisons. It looks like a simple map, but it is the backbone of the whole study.""",

81: """And here is the crucial detail, the source of the natural experiment. Within the pilot regions, the unexpected budget cut left five treated provinces still funded while their neighbors were dropped. The two images show the pilot regions and then the specific treated provinces inside them. Because the cut was driven by American budget politics, not by anything about the Italian firms, the treated and comparison provinces are genuinely comparable. This is the moment the endogeneity problem gets solved.""",

82: """Now the results, and they are dramatic. This chart shows firm survival: firms that received the management training were much more likely to still be alive years later than comparable firms that missed out. Point to the gap between the treatment and comparison provinces. Survival is the most basic measure of business success, and better management moved it substantially. This is not a small tweak; it is the difference between firms living and dying.""",

83: """The gains go well beyond survival. This chart tracks productivity, measured as TFPR, in the years after the intervention. The trained firms pulled clearly ahead, becoming more productive and selling more, and the gap widened over time rather than fading. That persistence is the striking part. A few weeks of learning how to run a factory better produced advantages that compounded for years.""",

84: """Now the comparison that makes the whole argument land. This chart isolates the effect of the technology transfer, the subsidized American machines, on its own. And the effect is small. New equipment by itself did not do much. Put this slide next to the previous two in your mind: management training produced large, lasting gains, while shiny new machines alone produced little. The lesson is that hardware without know-how is not worth much.""",

85: """So what actually changed inside the trained firms? The mechanisms are concrete. About 90 percent of the firms adopted the American management practices, and, remarkably, were still using them fifteen years later. They reorganized, with more managers relative to workers, and they took on more loans, invested more, and earned higher returns on assets. In short, the training did not just give them a one-time boost; it permanently changed how these companies were run.""",

86: """This chart backs up the persistence claim with detailed data, showing the share of firms using the American practices year by year. The point to make is that adoption rose and then stuck. Management practices, once genuinely learned and embedded, behave less like a fad and more like a durable technology. That durability is exactly why the productivity gains lasted.""",

87: """Let me pull the management story together, because it travels far beyond Italy. A program to upgrade managerial practices had a major, lasting impact on Italian firms' sales and productivity, which underlines how much sheer management quality matters, something economists long underweighted. And here is the punchline for a business school: Italy right after the war looked a lot like many developing countries today, so the finding suggests that teaching management, not just shipping capital, can be a powerful lever for development.""",

88: """One more featured paper, and it completes the postwar picture. This is "Reconstruction Aid, Public Infrastructure, and Economic Development," by Nicola Bianchi and Michela Giorcelli. Where the last paper was about the "software" of management inside firms, this one is about the "hardware," the roads, bridges, and power lines that the Marshall Plan also rebuilt. The next slide gives the headline result.""",

89: """This closes the Marshall Plan chapter with an important balancing point. The plan did not only reform firms; it also rebuilt physical infrastructure, roads, bridges, power, and water. Provinces that received more reconstruction grants went on to grow faster for decades, not just years. The deeper finding is that the two halves reinforced each other: infrastructure, the hardware, and management training, the software, were each more powerful because the other was there too. The image is the Autostrada del Sole. The takeaway on the slide says it well: rebuilding physical capital and know-how together is what drives lasting growth.""",

90: """All of that set the stage for one of the great growth stories of the twentieth century, the Italian economic miracle of roughly 1958 to 1963. The economy grew on the order of 6 to 8 percent a year, and Italy went from largely agrarian to industrial in a single generation. Millions moved from the south to the northern factories of Turin and Milan, and Italy started producing the icons the world still associates with it: the Vespa scooter, the Fiat 500, shown here, and household "white goods." The state built champions too, like the energy company ENI under Enrico Mattei, and opened the Autostrada del Sole in 1964.

ANECDOTE — The Vespa is a perfect symbol of the miracle. Its maker, Enrico Piaggio, is said to have taken one look at the buzzing little scooter and exclaimed that it looked like a wasp, "vespa" in Italian, and the name stuck. It put an entire nation on wheels cheaply, and when Audrey Hepburn rode one through Rome in the 1953 film Roman Holiday, it became a global emblem of Italian style.""",

91: """But Italy's industrial success is not only about big firms in the northwest. From the 1970s a "Third Italy" emerged in the center and northeast, built on clusters of small, family-owned firms, and it is central to what "Made in Italy" means. Point to the examples: textiles in Prato, ceramics in Sassuolo, eyewear in Belluno, home to Luxottica, packaging around Bologna. These districts combine flexible specialization, deep local know-how, and strong export niches, and, tellingly, they are rooted in the very same medieval traditions of the commune, the guild, and the family that we traced earlier. The image is a Murano glassmaker in Venice, a living example of that craft tradition.

ANECDOTE — Take Luxottica, in the small mountain province of Belluno. Its founder, Leonardo Del Vecchio, grew up partly in an orphanage in Milan and started out as a metal worker. He built Luxottica into the largest eyewear company on earth, making a huge share of the world's glasses and owning brands like Ray-Ban. Its merger created EssilorLuxottica, one of the companies on our visit list. A global giant grew out of an Alpine valley and a family firm.""",

93: """Now the Italian economy today, starting with the long view of growth. This chart shows GDP after the war: an extraordinary rise through the miracle years and beyond, and then, from around the year 2000, something troubling, stagnation. Trace the flattening at the end. That flat line is the central puzzle of modern Italy. A country that grew spectacularly for decades essentially stopped growing, and the rest of this section asks why.""",

94: """The stagnation looks even starker in comparison. Line Italy up against Germany and the United States and you see it fall behind again in recent decades, after having nearly caught up. This is not just slow growth in the abstract; it is Italy losing ground relative to its peers. Keep this picture in mind, because it frames the diagnosis that follows.""",

95: """Economists have a specific suspect for the stagnation: productivity. This chart shows total factor productivity, roughly how efficiently the economy turns inputs into output, and for Italy it has been essentially flat since the mid-1990s. That timing is a huge clue, because the mid-1990s is exactly when information technology began transforming other rich economies. The two candidate explanations on the slide, slow IT adoption and misallocation of resources, are what the next featured paper tries to disentangle.""",

96: """This is the fourth featured paper, and it tackles the puzzle head-on. It is called "Diagnosing the Italian Disease," by Bruno Pellegrino and Luigi Zingales. The title is deliberately clinical, treating slow growth as a disease to be diagnosed. Their answer is uncomfortable and specific, and it connects right back to themes we have seen all day, family, trust, and institutions.""",

97: """Here is their diagnosis in plain terms. Italy's productivity stopped growing in the mid-1990s, precisely when IT took off elsewhere, and the cause was largely internal, not global. Their argument is that Italy's characteristic family firms tend to promote managers on loyalty and family ties rather than on merit. So when these firms bought computers and software, they could not use them well, because the managers lacked the skills to exploit them. The takeaway is pointed: without meritocratic management, new technology simply does not pay off. Notice how this echoes the Marshall Plan finding, that management is the binding constraint.""",

98: """The old North-South divide is still very much alive, and this chart shows it in hard numbers, income per person by area. The gap between the wealthy north and the poorer south remains roughly two to one. Connect this back to the morning: this is the same divide we traced all the way to the medieval communes and the Norman south. Centuries of history are still visible in a single bar chart of incomes.""",

99: """One consequence of that stagnation is that Italy is losing its talent. The images and numbers tell it: Italy is among the EU countries sending the most workers abroad, and in 2024 around 156,000 citizens emigrated, a twenty-five-year high, with university graduates especially likely to leave. New research links this graduate emigration to fewer start-ups being created back home. It is a worrying feedback loop, where a slow economy pushes out exactly the people who might have energized it.""",

100: """Corruption and weak institutions are part of the same picture. On Transparency International's 2024 index Italy ranks 52nd of 180 countries, and 19th of 27 within the EU, having dropped ten places against the previous year. The images make the theme concrete. This is not just a moral issue; weak rule of law and corruption are a direct tax on doing business, and they help explain the misallocation and the stagnation we just saw.

ANECDOTE — Italy does have a powerful counter-tradition of fighting back. In the early 1990s a set of investigations known as "Mani Pulite," or "Clean Hands," exposed a vast web of political bribery nicknamed "Tangentopoli," or "Bribe City." It brought down essentially the entire postwar party system almost overnight. It showed both how deep the corruption ran and how fiercely parts of the Italian state were willing to confront it.""",

101: """Let's end the diagnosis on a genuine strength, because Italy's brands are world-beating. The images are a wall of names you know, and the prominent sectors are on the slide: food, tourism, fashion, and luxury cars. Much of this is powered by family firms and mid-sized "pocket multinationals," what economists have called Italy's "fourth capitalism," companies that are small by global standards but absolutely dominant in their niches. This is the paradox in miniature: the same family-firm model that holds productivity back also produces some of the most admired products on earth.""",

102: """This slide is the synthesis of the whole day, so take your time. On one side are Italy's strengths: design and craftsmanship, globally dominant brands in fashion, food, luxury cars, and machinery, resilient family firms, and the industrial districts of "Made in Italy." On the other side are the constraints we have documented: flat productivity since the mid-1990s, firms that stay small and often promote on loyalty over merit, the persistent North-South divide, and demographic decline, brain drain, and weak institutions. The line that sums it up is that Italy's excellence is sectoral and relational, brilliant in particular products and particular places, while scale and institutions are the persistent weak spots. Hold this tension in mind, because it is exactly what we will probe with the companies and speakers we meet.""",

103: """We close with a quick exercise to consolidate the day, and to prime you for the trip. Think of it as "the good, the bad, and the ugly" of the Italian economy. I want two examples of each: two genuine strengths, two real weaknesses, and two things that are frankly dysfunctional. There are no perfect answers here. The goal is to get you weighing the evidence yourself, because that is exactly the judgment you will need when we are sitting across from Italian executives.""",

104: """That is the arc, from the Etruscans to EssilorLuxottica. Thank you. When we land in Milan and Turin, everything we saw today, the pull of the sea, the legacy of the self-governing cities, the late industrialization, the power of management, and the paradox of world-class brands inside a stalled economy, will be right in front of us. Come with questions, and let's go see it for ourselves.""",
}

# Backup slides: one brief orienting line each (105-131; 132 is a poll).
BACKUP = {
105: "Backup slides. Reference material shown only on demand, not part of the main flow.",
106: "Backup: the detailed day-by-day itinerary for the trip, September 6 to 12. Linked from the Schedule on the logistics slide.",
107: "Backup: the group-presentation topics and the list of companies to choose from. Linked from the presentation logistics slide.",
108: "Backup: Villa Campari, the historic Campari estate near Milan. Reference for the company visit and presentation option.",
109: "Backup: Manifattura Automobili Torino, a Turin coachbuilder and small-series supercar maker. Reference for a company visit.",
110: "Backup: the Sassi of Matera. Reference photo for the early-settlement discussion.",
111: "Backup: the prehistoric rock carvings of Valcamonica. Reference photo for the early-settlement discussion.",
112: "Backup: a close-up of the Valcamonica petroglyphs, including the figure nicknamed 'The Astronaut.'",
113: "Backup: a map of Etruscan and Greek territories and trade routes, including Magna Graecia in the south.",
114: "Backup: the Chimera of Arezzo, a masterpiece of Etruscan bronze casting.",
115: "Backup: San Marino, perched on Monte Titano, one of the world's oldest surviving republics.",
116: "Backup: a historical map of the Italian peninsula around 876 AD, part of a sequence showing how Italy's political map kept changing.",
117: "Backup: a historical map of Italy around 1100.",
118: "Backup: a map of the member cities of the Lombard League. Reference for the communes discussion.",
119: "Backup: original nineteenth-century opera librettos and scores. Reference for the copyright-and-creativity study.",
120: "Backup: how the opera study measured 'quality' — listings in the Annals of Opera, performances at the Met, and recordings available today.",
121: "Backup: a map of Italy in 477 AD, under Odoacer, just after the Western Empire fell.",
122: "Backup: a map of Italy in 592, fragmented among Lombards, Byzantines, and Franks.",
123: "Backup: a map of Italy in 853.",
124: "Backup: a map of Italy in 1052.",
125: "Backup: a map of Italy in 1100.",
126: "Backup: a map of Italy in 1494, the age of the city-states on the eve of foreign invasion.",
127: "Backup: a map of Italy in 1699.",
128: "Backup: a map of Italy in 1789, on the eve of Napoleon.",
129: "Backup: a map of Italy in 1811, at the height of Napoleon's reorganization of the peninsula.",
130: "Backup: a map of Italy in 1830, the restored patchwork before unification.",
131: "Backup: a map of Italy in 1870, finally unified into a single state.",
}
