"""One-off: capture the ORIGINAL deck's speaker notes verbatim into
`_m4_notes.py`, keyed by the original display slide number.

The rebuild carries substantive notes over unchanged (Teaching CLAUDE.md:
"preserve substantive notes from the original verbatim"), so they are
copied out of `Module 4.pptx` rather than retyped.

Run once, by path.
"""
from pathlib import Path
from pptx import Presentation

SRC = Path(__file__).parent / "Module 4.pptx"
DST = Path(__file__).parent / "_m4_notes.py"

HEADER = '''# ==========================================================================
#  _m4_notes.py — speaker notes of the ORIGINAL "Module 4.pptx", verbatim.
#
#  Generated by _make_notes.py; keyed by the ORIGINAL display slide number.
#  Do not hand-edit: regenerate instead, or override in _build_Module4.py.
# ==========================================================================

NOTES = {
'''


def main():
    prs = Presentation(str(SRC))
    out = [HEADER]
    n = 0
    for i, s in enumerate(prs.slides, 1):
        if not s.has_notes_slide:
            continue
        tf = s.notes_slide.notes_text_frame
        if tf is None:
            continue
        txt = tf.text.strip()
        if not txt:
            continue
        # PollEverywhere notes are part of the poll mechanism and travel
        # with the spliced slide; they must never be re-emitted here.
        if "polleverywhere.com" in txt.lower():
            continue
        n += 1
        out.append("    %d: %r,\n" % (i, txt))
    out.append("}\n")
    DST.write_text("".join(out), encoding="utf-8")
    print(f"wrote {DST.name}: {n} notes")


if __name__ == "__main__":
    main()
